### PR TITLE
[Task] change description of reputation/thanks text popup

### PR DESCRIPTION
**Pull request by zag2me**
Update the rest of the "thanks" text popup to make it consistent.

### CODE REVIEW

**Comment by zag2me** [comment]
@da-anda hopefully I did this right.

**Comment by da-anda** [comment]
Ideally you move the changed labels from inc/languages/english/reputation.lang.php to the xbmc language file so that the change will be persisted on forum updates

**Comment by zag2me** [comment]
Ahh makes sense, OK will try to fix

**Comment by zag2me** [comment]
Should be fixed, now if only I can work out how to squash those commits with tortoise git! The "combine to one commit" context menu on the "show log" seems to have disappeared. grrr

**Comment by da-anda** [comment]
you could have used "ammend" checkbox in the commit dialog in order to modify your last commit in current branch with local changes. Now you have to do a rebase (you probably have to check the "force" checkbox), rightclick on the commits you don't want anymore (like the "merge branch") and set those to "skip". In order to squash a commit with the previous (below one) one in the list, rightclick on the above and set it to "merge".
In order to update the PR on github correctly you then have to do a forcepush to your(!!!!!) github repo.

**Pull request closed without merging**
