### PR TITLE
optimize png images losslessly using zopflipng

### PR DESCRIPTION
**Pull request by PeterDaveHello**
192 images optimized losslessly using Google's zopflipng
```
 admin/jscripts/codepress/images/line-numbers.png | Bin 16556 -> 10047 bytes
 admin/styles/default/images/border-corners.png   | Bin 3627 -> 3323 bytes
 admin/styles/default/images/border-sides.png     | Bin 2931 -> 2830 bytes
 admin/styles/default/images/border-topbottom.png | Bin 2910 -> 2809 bytes
 images/avatars/xbmc-addict.png                   | Bin 3096 -> 2160 bytes
 images/avatars/xbmc-fan.png                      | Bin 3006 -> 2075 bytes
 images/avatars/xbmc-junkie.png                   | Bin 3164 -> 2135 bytes
 images/avatars/xbmc-nerd.png                     | Bin 3036 -> 2103 bytes
 images/avatars/xbmc-skinner.png                  | Bin 3211 -> 2259 bytes
 images/goodbyespammer_postbit.png                | Bin 729 -> 645 bytes
 images/minimal/adv.png                           | Bin 1390 -> 402 bytes
 images/minimal/alt2_button_bg.png                | Bin 931 -> 79 bytes
 images/minimal/alt_button_bg.png                 | Bin 957 -> 105 bytes
 images/minimal/button_bg.png                     | Bin 971 -> 115 bytes
 images/minimal/button_bg1.png                    | Bin 975 -> 98 bytes
 images/minimal/input_login.png                   | Bin 1343 -> 472 bytes
 images/minimal/input_password.png                | Bin 1409 -> 536 bytes
 images/minimal/lockbutton_bg.png                 | Bin 954 -> 102 bytes
 images/minimal/logo.png                          | Bin 2006 -> 688 bytes
 images/minimal/modcp/announcements.png           | Bin 284 -> 184 bytes
 images/minimal/modcp/banning.png                 | Bin 251 -> 162 bytes
 images/minimal/modcp/editprofile.png             | Bin 251 -> 162 bytes
 images/minimal/modcp/home.png                    | Bin 265 -> 157 bytes
 images/minimal/modcp/ipsearch.png                | Bin 328 -> 204 bytes
 images/minimal/modcp/modlogs.png                 | Bin 269 -> 187 bytes
 images/minimal/modcp/modqueue.png                | Bin 208 -> 136 bytes
 images/minimal/modcp/reports.png                 | Bin 290 -> 169 bytes
 images/minimal/modcp/warninglogs.png             | Bin 287 -> 186 bytes
 images/minimal/rtt.png                           | Bin 1305 -> 298 bytes
 images/minimal/usercp/attachments.png            | Bin 291 -> 174 bytes
 images/minimal/usercp/avatar.png                 | Bin 201 -> 133 bytes
 images/minimal/usercp/composepm.png              | Bin 232 -> 153 bytes
 images/minimal/usercp/drafts.png                 | Bin 208 -> 136 bytes
 images/minimal/usercp/editfolders.png            | Bin 193 -> 117 bytes
 images/minimal/usercp/editlists.png              | Bin 302 -> 190 bytes
 images/minimal/usercp/editsig.png                | Bin 260 -> 170 bytes
 images/minimal/usercp/email.png                  | Bin 232 -> 153 bytes
 images/minimal/usercp/fsubscriptions.png         | Bin 146 -> 96 bytes
 images/minimal/usercp/home.png                   | Bin 265 -> 157 bytes
 images/minimal/usercp/notepad.png                | Bin 208 -> 136 bytes
 images/minimal/usercp/options.png                | Bin 330 -> 185 bytes
 images/minimal/usercp/password.png               | Bin 318 -> 194 bytes
 images/minimal/usercp/pmfolder.png               | Bin 193 -> 117 bytes
 images/minimal/usercp/pmtracking.png             | Bin 320 -> 211 bytes
 images/minimal/usercp/profile.png                | Bin 251 -> 162 bytes
 images/minimal/usercp/subscriptions.png          | Bin 145 -> 98 bytes
 images/minimal/usercp/trash_pmfolder.png         | Bin 226 -> 152 bytes
 images/minimal/usercp/usergroups.png             | Bin 251 -> 162 bytes
 images/minimal/usercp/username.png               | Bin 251 -> 162 bytes
 images/minimal/usercp/viewprofile.png            | Bin 251 -> 162 bytes
 images/smilies/airplane.png                      | Bin 992 -> 890 bytes
 images/smilies/angel.png                         | Bin 1550 -> 1530 bytes
 images/smilies/angry.png                         | Bin 1373 -> 1368 bytes
 images/smilies/announce.png                      | Bin 1434 -> 1424 bytes
 images/smilies/beer.png                          | Bin 1400 -> 1396 bytes
 images/smilies/blush.png                         | Bin 1418 -> 1405 bytes
 images/smilies/bomb.png                          | Bin 1221 -> 1098 bytes
 images/smilies/bowl.png                          | Bin 1448 -> 1427 bytes
 images/smilies/brb.png                           | Bin 630 -> 591 bytes
 images/smilies/bug-eyes.png                      | Bin 1378 -> 1234 bytes
 images/smilies/bunny.png                         | Bin 1392 -> 1392 bytes
 images/smilies/bye.png                           | Bin 1467 -> 1459 bytes
 images/smilies/camera.png                        | Bin 984 -> 893 bytes
 images/smilies/can.png                           | Bin 902 -> 812 bytes
 images/smilies/car.png                           | Bin 1241 -> 1241 bytes
 images/smilies/cat2.png                          | Bin 1277 -> 1243 bytes
 images/smilies/chick.png                         | Bin 1160 -> 1055 bytes
 images/smilies/chicken.png                       | Bin 1245 -> 1085 bytes
 images/smilies/chicken2.png                      | Bin 1215 -> 1178 bytes
 images/smilies/cigarette.png                     | Bin 1307 -> 1156 bytes
 images/smilies/clock.png                         | Bin 1267 -> 1145 bytes
 images/smilies/cloudy.png                        | Bin 1049 -> 876 bytes
 images/smilies/clover.png                        | Bin 1498 -> 1485 bytes
 images/smilies/clown.png                         | Bin 1216 -> 1105 bytes
 images/smilies/coffee.png                        | Bin 1503 -> 1500 bytes
 images/smilies/computer.png                      | Bin 933 -> 791 bytes
 images/smilies/confused.png                      | Bin 1399 -> 1394 bytes
 images/smilies/console.png                       | Bin 1032 -> 914 bytes
 images/smilies/cool.png                          | Bin 1398 -> 1395 bytes
 images/smilies/cow.png                           | Bin 1081 -> 944 bytes
 images/smilies/cow2.png                          | Bin 1521 -> 1496 bytes
 images/smilies/crying.png                        | Bin 1425 -> 1422 bytes
 images/smilies/curl-lip.png                      | Bin 1396 -> 1391 bytes
 images/smilies/disdain.png                       | Bin 1432 -> 1429 bytes
 images/smilies/doctor.png                        | Bin 1238 -> 1109 bytes
 images/smilies/dog2.png                          | Bin 1418 -> 1379 bytes
 images/smilies/dont-know.png                     | Bin 1368 -> 1364 bytes
 images/smilies/drink.png                         | Bin 1184 -> 1076 bytes
 images/smilies/eat.png                           | Bin 1494 -> 1492 bytes
 images/smilies/evil-grin.png                     | Bin 1366 -> 1235 bytes
 images/smilies/eyeroll.png                       | Bin 1353 -> 1353 bytes
 images/smilies/female.png                        | Bin 1121 -> 980 bytes
 images/smilies/film.png                          | Bin 1570 -> 1569 bytes
 images/smilies/fingers-xd.png                    | Bin 1460 -> 1443 bytes
 images/smilies/flag-us.png                       | Bin 455 -> 413 bytes
 images/smilies/foot-in-mouth.png                 | Bin 1388 -> 1382 bytes
 images/smilies/frown.png                         | Bin 1397 -> 1391 bytes
 images/smilies/ghost.png                         | Bin 1185 -> 1033 bytes
 images/smilies/grin.png                          | Bin 1368 -> 1235 bytes
 images/smilies/hammer.png                        | Bin 976 -> 832 bytes
 images/smilies/handcuffs.png                     | Bin 1480 -> 1458 bytes
 images/smilies/handshake.png                     | Bin 1442 -> 1436 bytes
 images/smilies/heart-broken.png                  | Bin 1301 -> 1266 bytes
 images/smilies/heart.png                         | Bin 1243 -> 1211 bytes
 images/smilies/highfive.png                      | Bin 1528 -> 1512 bytes
 images/smilies/hippo.png                         | Bin 1388 -> 1365 bytes
 images/smilies/kissed.png                        | Bin 1387 -> 1380 bytes
 images/smilies/kissing.png                       | Bin 1318 -> 1281 bytes
 images/smilies/knife.png                         | Bin 1074 -> 914 bytes
 images/smilies/koala.png                         | Bin 1470 -> 1417 bytes
 images/smilies/lamp.png                          | Bin 1313 -> 1140 bytes
 images/smilies/liquor.png                        | Bin 592 -> 571 bytes
 images/smilies/loser.png                         | Bin 1392 -> 1361 bytes
 images/smilies/lying.png                         | Bin 1381 -> 1374 bytes
 images/smilies/mail.png                          | Bin 786 -> 717 bytes
 images/smilies/male.png                          | Bin 1217 -> 1103 bytes
 images/smilies/mean.png                          | Bin 1402 -> 1401 bytes
 images/smilies/mobile.png                        | Bin 621 -> 596 bytes
 images/smilies/moneymouth.png                    | Bin 1430 -> 1425 bytes
 images/smilies/monkey.png                        | Bin 1151 -> 1034 bytes
 images/smilies/monkey2.png                       | Bin 1460 -> 1437 bytes
 images/smilies/moon.png                          | Bin 1326 -> 1217 bytes
 images/smilies/mouse.png                         | Bin 1429 -> 1389 bytes
 images/smilies/music.png                         | Bin 1553 -> 1532 bytes
 images/smilies/nathan.png                        | Bin 4205 -> 4060 bytes
 images/smilies/pain.png                          | Bin 1387 -> 1387 bytes
 images/smilies/panda.png                         | Bin 1294 -> 1260 bytes
 images/smilies/party.png                         | Bin 1509 -> 1495 bytes
 images/smilies/phone.png                         | Bin 1167 -> 1048 bytes
 images/smilies/pig.png                           | Bin 1233 -> 1211 bytes
 images/smilies/pig2.png                          | Bin 1434 -> 1432 bytes
 images/smilies/pill.png                          | Bin 975 -> 842 bytes
 images/smilies/pissed-off.png                    | Bin 1300 -> 1290 bytes
 images/smilies/pizza.png                         | Bin 1012 -> 880 bytes
 images/smilies/plate.png                         | Bin 1342 -> 1321 bytes
 images/smilies/poop.png                          | Bin 1214 -> 1077 bytes
 images/smilies/pray.png                          | Bin 1449 -> 1433 bytes
 images/smilies/present.png                       | Bin 1200 -> 1093 bytes
 images/smilies/pumpkin.png                       | Bin 1326 -> 1320 bytes
 images/smilies/quiet.png                         | Bin 1385 -> 1381 bytes
 images/smilies/rain.png                          | Bin 1287 -> 1126 bytes
 images/smilies/rainbow.png                       | Bin 667 -> 577 bytes
 images/smilies/razz.png                          | Bin 1427 -> 1426 bytes
 images/smilies/reindeer.png                      | Bin 1274 -> 1221 bytes
 images/smilies/rose-dead.png                     | Bin 1074 -> 960 bytes
 images/smilies/rose.png                          | Bin 905 -> 779 bytes
 images/smilies/rotfl.png                         | Bin 1538 -> 1522 bytes
 images/smilies/search.png                        | Bin 908 -> 835 bytes
 images/smilies/secret.png                        | Bin 1434 -> 1434 bytes
 images/smilies/sheep.png                         | Bin 1332 -> 1320 bytes
 images/smilies/sheep2.png                        | Bin 1290 -> 1193 bytes
 images/smilies/shock.png                         | Bin 1381 -> 1379 bytes
 images/smilies/shout.png                         | Bin 1349 -> 1202 bytes
 images/smilies/silly.png                         | Bin 1389 -> 1382 bytes
 images/smilies/skeleton.png                      | Bin 1248 -> 1162 bytes
 images/smilies/sleepy.png                        | Bin 1455 -> 1447 bytes
 images/smilies/smile-big.png                     | Bin 1389 -> 1388 bytes
 images/smilies/smirk.png                         | Bin 1365 -> 1360 bytes
 images/smilies/snail.png                         | Bin 1246 -> 1245 bytes
 images/smilies/snicker.png                       | Bin 1346 -> 1203 bytes
 images/smilies/snowman.png                       | Bin 1239 -> 1142 bytes
 images/smilies/soccerball.png                    | Bin 1300 -> 1286 bytes
 images/smilies/soldier.png                       | Bin 1449 -> 1426 bytes
 images/smilies/star.png                          | Bin 1282 -> 1168 bytes
 images/smilies/starving.png                      | Bin 1475 -> 1470 bytes
 images/smilies/stop.png                          | Bin 1431 -> 1411 bytes
 images/smilies/sun.png                           | Bin 1510 -> 1459 bytes
 images/smilies/sweat.png                         | Bin 1404 -> 1402 bytes
 images/smilies/talktohand.png                    | Bin 1454 -> 1450 bytes
 images/smilies/teeth.png                         | Bin 1286 -> 1141 bytes
 images/smilies/thinking.png                      | Bin 1396 -> 1389 bytes
 images/smilies/thumbs-down.png                   | Bin 1092 -> 981 bytes
 images/smilies/thumbs-up.png                     | Bin 1099 -> 981 bytes
 images/smilies/thunder.png                       | Bin 1222 -> 1065 bytes
 images/smilies/tiger.png                         | Bin 1434 -> 1376 bytes
 images/smilies/time-out.png                      | Bin 1352 -> 1350 bytes
 images/smilies/tremble.png                       | Bin 1360 -> 1358 bytes
 images/smilies/turtle.png                        | Bin 1281 -> 1279 bytes
 images/smilies/tv.png                            | Bin 559 -> 510 bytes
 images/smilies/umbrella.png                      | Bin 1221 -> 1038 bytes
 images/smilies/victory.png                       | Bin 1434 -> 1427 bytes
 images/smilies/watermelon.png                    | Bin 1179 -> 1095 bytes
 images/smilies/weep.png                          | Bin 1363 -> 1356 bytes
 images/smilies/yin-yang.png                      | Bin 1067 -> 984 bytes
 images/smilies/zombie-killer.png                 | Bin 1364 -> 1363 bytes
 mobiquo/emoji/iphone_emoji.png                   | Bin 360674 -> 346786 bytes
 mobiquo/images/byo-online.png                    | Bin 1049 -> 152 bytes
 mobiquo/images/tapatalk-online.png               | Bin 1430 -> 515 bytes
 mobiquo/smartbanner/x.png                        | Bin 1209 -> 254 bytes
 xbmc/images/arrow-down.png                       | Bin 971 -> 115 bytes
 xbmc/images/logo-sbs-black.png                   | Bin 2172 -> 1630 bytes
 xbmc/images/logo-sbs-white.png                   | Bin 6666 -> 5812 bytes
```

### CODE REVIEW

**Comment by fritsch** [comment]
Thx much. It's something for the webguys @zag2me @da-anda please decided if you prefer small file size vs. higher cpu load when decoding :-)

**Comment by da-anda** [comment]
well, it's touching upstream pics for mybb and tapatalk which might be reverted to their defaults on next updates in case I forget to exclude these, but besides of that, I don't mind either way. Files will usually only be loaded once and from there on come from the browser cache, but sure, why not save some bytes.

Odd that I didn't get a github notification on that one. Need to check my settings.

**Comment by hudokkow** [comment]
Probably not your settings. GitHub is confused. I didn't get notifications for a couple of PRs I'm subscribed to.
I blame the unicorns...

**Comment by PeterDaveHello** [comment]
@da-anda I also sent a PR to mybb:
https://github.com/mybb/mybb/pull/2407

Once they accepted that, the new versions will come with the optimized images!

**Pull request merged**
